name: Auto Build ShellCrash

on:
  workflow_dispatch:

env:
  IMAGE_NAME: seansuny/shellcrash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract ShellCrash Version
        id: get_version
        run: |
          VERSION_URL="https://raw.githubusercontent.com/juewuy/ShellCrash/master/version"
          VERSION=$(curl -sL --retry 3 "$VERSION_URL" | tr -d '\n\r')
          
          if [ -z "$VERSION" ]; then
            echo "❌ 无法获取版本号，终止构建！"
            exit 1
          fi
          echo "✅ 检测到 ShellCrash 版本: $VERSION"
          echo "OFFICIAL_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check Docker Hub Tag
        id: check_tag
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/tags/${{ env.OFFICIAL_VERSION }}/)
          
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "EXISTS=true" >> $GITHUB_ENV
            echo "⚠️ Docker Hub 上已存在版本 ${{ env.OFFICIAL_VERSION }}，跳过构建！"
          else
            echo "EXISTS=false" >> $GITHUB_ENV
            echo "✅ 最新的版本 ${{ env.OFFICIAL_VERSION }}，准备构建！"
          fi

      - name: Set up QEMU
        if: env.EXISTS == 'false'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: env.EXISTS == 'false'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: env.EXISTS == 'false'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        if: env.EXISTS == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.OFFICIAL_VERSION }}
          build-args: |
            VERSION=${{ env.OFFICIAL_VERSION }}
